---
services:
  mcp-todo-dev:
    image: node:22-alpine
    working_dir: /app
    ports:
      - '${SERVER_PORT:-3300}:3300'
    environment:
      - NODE_ENV=development
      - SERVER_PORT=${SERVER_PORT:-3300}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - AI_ANALYSIS_ENABLED=${AI_ANALYSIS_ENABLED:-false}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_MODEL=${OPENAI_MODEL}
    volumes:
      - ./:/app
      - app_node_modules:/app/node_modules
      - mcp_db:/home/node/.mcp-todo-server
    command: sh -c "apk add --no-cache python3 make g++ && npm install && npx tsx watch src/todo-server.ts"

volumes:
  app_node_modules:
  mcp_db:
